spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/valora
    username: valora
    password: valora
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:troque-esta-chave}
    issuer: valora-api
